extend-include = ["*.ipynb"]

# Match PEP-8 guidelines
line-length = 79
indent-width = 4

# Python version
target-version = "py311"

# Verbose error output
output-format = "full"

[lint]
select = ["ALL"]
ignore = [
    # modules
    "DJ",  # Django
    "EXE", # Executables

    # specifics
    "D100", # --- Missing docstrings ---
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107", # --- Missing docstrings ---
    "D205", # Blank between summary and description
    "D212", # Multi-line docstring summary should start at the first line
    "D401", # First line should be in imperative mood
    "D415", # First line should end with punctuation
    "E402", # False positives for local imports
    "Q000", # Double quotes preferred over single quotes
    "TD002", # Missing TODO author
    "TD003", # Missing TODO link on following line
    "FIX002", # Too verbose descriptions of TODOs
]

[lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101", # Assert statements are fine in tests
    "S311", # Pseudo-RNG are fine in tests
    "PLR2004", # Magic value comparisons are fine in tests
]
"scratch.ipynb" = [
    "S101", # Assert statements are fine in scratch file
    "S311", # Pseudo-RNG are fine in scratch file
    "PLR2004", # Magic value comparisons are fine in scratch file
]
